// Package fakewallapop is a real HTTP server that answers like Wallapop's API
// host, web host and PubNub, with the response shapes recorded on 2026-09-14
// and enough mutable state that writes are observable. Tests point the three
// WALLAPOP_*_BASE_URL variables at one instance.
package fakewallapop

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"strings"
	"sync"
	"time"
)

const (
	ValidCookie   = "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..valid-session.cookie-value-that-is-long-enough-to-look-like-a-jwe-0123456789abcdef"
	RotatedCookie = "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..rotated-session.cookie-value-that-is-long-enough-to-look-like-a-jwe-0123456789abcdef"
	UserHash      = "kmznw7w2k7zn"
	OtherHash     = "p8j35kmwr7z9"
	// SavedSearchID is the one saved search the fake account owns.
	SavedSearchID = "a456aa5a-3d86-49bd-a8ca-504f410b127c"
)

// Item is the fake's canonical listing; every endpoint renders from it.
type Item struct {
	Hash        string
	Slug        string
	Title       string
	Description string
	Price       float64
	Condition   string
	Images      int
	Seller      string
	Reserved    bool
	Sold        bool
	Removed     bool // page 404s, API detail 404s
	Modified    time.Time
}

type Conversation struct {
	Hash     string
	Item     string
	Other    string
	Channel  string
	Unread   int
	Archived bool
	Messages []Message
}

type Message struct {
	ID        string
	FromSelf  bool
	Text      string
	At        time.Time
	TimeToken string
}

// Published is one PubNub publish the fake received.
type Published struct {
	Channel string
	Message map[string]any
	Meta    map[string]any
	UUID    string
}

type Request struct {
	Method string
	Path   string
	Query  url.Values
	UA     string
	Auth   string
}

type Server struct {
	*httptest.Server
	mu sync.Mutex

	Items         map[string]*Item
	SearchOrder   []string // hashes returned by search, in order; 40 per page
	Favorites     map[string]bool
	Conversations map[string]*Conversation
	Published     []Published
	Actions       []map[string]any // message actions (seen/received)
	Requests      []Request

	// Failure knobs.
	BlockNextAPI  bool // next api.wallapop.com request gets a CloudFront 403
	MintEmpty     bool // /api/auth/session answers {} (invalid session)
	MalformedItem bool // /api/v3/items/{hash} answers non-JSON
	CreateCalls   int
	Uploads       map[string]int // pictures received per upload id
	WebhookStatus int            // status for POST /hook (0 = 200)
	Hooks         []json.RawMessage
}

func New() *Server {
	s := &Server{
		Items:         map[string]*Item{},
		Favorites:     map[string]bool{},
		Conversations: map[string]*Conversation{},
	}
	s.Server = httptest.NewServer(http.HandlerFunc(s.handle))
	return s
}

// Env returns the variables that point the CLI at this fake.
func (s *Server) Env() map[string]string {
	return map[string]string{
		"WALLAPOP_API_BASE_URL":    s.URL,
		"WALLAPOP_WEB_BASE_URL":    s.URL,
		"WALLAPOP_PUBNUB_BASE_URL": s.URL,
	}
}

func (s *Server) AddItem(it Item) *Item {
	s.mu.Lock()
	defer s.mu.Unlock()
	if it.Slug == "" {
		it.Slug = strings.ToLower(strings.ReplaceAll(it.Title, " ", "-")) + "-1301645280"
	}
	if it.Seller == "" {
		it.Seller = OtherHash
	}
	if it.Modified.IsZero() {
		it.Modified = time.Date(2026, 9, 14, 10, 0, 0, 0, time.UTC)
	}
	cp := it
	s.Items[it.Hash] = &cp
	s.SearchOrder = append(s.SearchOrder, it.Hash)
	return &cp
}

func (s *Server) AddConversation(c Conversation) *Conversation {
	s.mu.Lock()
	defer s.mu.Unlock()
	if c.Channel == "" {
		c.Channel = "chat." + c.Other + "." + c.Item + "." + UserHash
	}
	if c.Other == "" {
		c.Other = OtherHash
	}
	cp := c
	s.Conversations[c.Hash] = &cp
	return &cp
}

// RequestsTo returns the recorded requests with exactly this path.
func (s *Server) RequestsTo(path string) []Request {
	s.mu.Lock()
	defer s.mu.Unlock()
	var out []Request
	for _, r := range s.Requests {
		if r.Path == path {
			out = append(out, r)
		}
	}
	return out
}

// RequestsUnder returns the recorded requests whose path starts with prefix.
func (s *Server) RequestsUnder(prefix string) []Request {
	s.mu.Lock()
	defer s.mu.Unlock()
	var out []Request
	for _, r := range s.Requests {
		if strings.HasPrefix(r.Path, prefix) {
			out = append(out, r)
		}
	}
	return out
}

func (s *Server) handle(w http.ResponseWriter, r *http.Request) {
	s.mu.Lock()
	s.Requests = append(s.Requests, Request{Method: r.Method, Path: r.URL.Path, Query: r.URL.Query(), UA: r.UserAgent(), Auth: r.Header.Get("Authorization")})
	block := s.BlockNextAPI && strings.HasPrefix(r.URL.Path, "/api/v3/")
	if block {
		s.BlockNextAPI = false
	}
	s.mu.Unlock()
	if block {
		w.WriteHeader(http.StatusForbidden)
		fmt.Fprint(w, "<html><body><h1>403 ERROR</h1><p>The request could not be satisfied.</p>Generated by cloudfront (CloudFront)</body></html>")
		return
	}
	p := r.URL.Path
	switch {
	case p == "/api/auth/session":
		s.session(w, r)
	case p == "/api/v3/search":
		s.search(w, r)
	case p == "/api/v3/search/filters/regular-filters":
		s.filters(w, r)
	case strings.HasPrefix(p, "/api/v3/searchalerts/savedsearch/"):
		s.savedSearches(w, r)
	case p == "/api/v3/categories":
		s.categories(w, r)
	case p == "/api/v3/users/me":
		if !s.authed(w, r) {
			return
		}
		writeJSON(w, 200, s.rawUser(UserHash, "Test User", "test-user-1"))
	case strings.HasPrefix(p, "/api/v3/users/"):
		s.users(w, r)
	case p == "/api/v3/user/items", p == "/api/v3/user/items/sold", p == "/api/v3/user/items/favorited":
		if !s.authed(w, r) {
			return
		}
		s.mu.Lock()
		var data []map[string]any
		for _, h := range s.SearchOrder {
			it := s.Items[h]
			if p == "/api/v3/user/items/favorited" && s.Favorites[h] || p != "/api/v3/user/items/favorited" && it.Seller == UserHash && it.Sold == strings.HasSuffix(p, "/sold") {
				data = append(data, s.userItemJSON(it))
			}
		}
		s.mu.Unlock()
		if data == nil {
			data = []map[string]any{}
		}
		writeJSON(w, 200, map[string]any{"data": data, "meta": map[string]any{}})
	case p == "/api/v3/items" && r.Method == http.MethodPost:
		s.createItem(w, r)
	case p == "/api/v3/items/upload/components":
		if !s.authed(w, r) {
			return
		}
		writeJSON(w, 200, map[string]any{"components": []any{}})
	case strings.HasPrefix(p, "/api/v3/upload/") && strings.HasSuffix(p, "/pictures"):
		if !s.authed(w, r) {
			return
		}
		id := strings.TrimSuffix(strings.TrimPrefix(p, "/api/v3/upload/"), "/pictures")
		s.mu.Lock()
		if s.Uploads == nil {
			s.Uploads = map[string]int{}
		}
		s.Uploads[id]++
		s.mu.Unlock()
		w.WriteHeader(204)
	case strings.HasPrefix(p, "/api/v3/items/"):
		s.items(w, r)
	case strings.HasPrefix(p, "/item/"):
		s.itemPage(w, r)
	case strings.HasPrefix(p, "/user/"):
		s.userPage(w, r)
	case p == "/bff/messaging/inbox" || p == "/bff/messaging/archived":
		s.inbox(w, r, p == "/bff/messaging/archived")
	case strings.HasPrefix(p, "/bff/messaging/conversation/"):
		s.conversation(w, r)
	case strings.HasPrefix(p, "/api/v3/instant-messaging/archive/conversation/"):
		if !s.authed(w, r) {
			return
		}
		writeJSON(w, 200, map[string]any{"messages": []any{}, "next_from": ""})
	case p == "/api/v3/instant-messaging/token":
		if !s.authed(w, r) {
			return
		}
		writeJSON(w, 201, map[string]any{"token": "pam-token", "channels": []string{"inbox." + UserHash, "signals." + UserHash}})
	case p == "/api/v3/instant-messaging/conversation":
		s.createConversation(w, r)
	case p == "/api/v3/instant-messaging/conversations/archive", p == "/api/v3/instant-messaging/conversations/unarchive":
		s.archive(w, r, strings.HasSuffix(p, "/archive"))
	case p == "/api/v3/instant-messaging/messages/unread":
		writeJSON(w, 200, map[string]any{"unread_counter": 0})
	case strings.HasPrefix(p, "/publish/"):
		s.publish(w, r)
	case strings.HasPrefix(p, "/v2/subscribe/"):
		s.subscribe(w, r)
	case strings.HasPrefix(p, "/v1/message-actions/"):
		s.messageAction(w, r)
	case p == "/hook" || strings.HasPrefix(p, "/ntfy/"):
		s.hook(w, r)
	default:
		writeJSON(w, 404, map[string]any{"code": 0, "message": "not found", "type": 0})
	}
}

// owned mirrors Wallapop's answer to an authenticated write on someone else's
// item, recorded 2026-09-15: a bare 401 for reserve and delete, 403 for sold,
// no body. Unauthenticated foreign writes were not exercised, so authed runs
// first by assumption.
func (s *Server) owned(w http.ResponseWriter, it *Item, status int) bool {
	if it.Seller == UserHash {
		return true
	}
	w.WriteHeader(status)
	return false
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func (s *Server) authed(w http.ResponseWriter, r *http.Request) bool {
	if r.Header.Get("Authorization") != "Bearer access-token" {
		writeJSON(w, 401, map[string]any{"code": 401, "message": "unauthorized"})
		return false
	}
	return true
}

func (s *Server) session(w http.ResponseWriter, r *http.Request) {
	s.mu.Lock()
	empty := s.MintEmpty
	s.mu.Unlock()
	cookie := ""
	for _, c := range r.Cookies() {
		if c.Name == "__Secure-next-auth.session-token" {
			cookie = c.Value
		}
	}
	if empty || (cookie != ValidCookie && cookie != RotatedCookie) {
		writeJSON(w, 200, map[string]any{})
		return
	}
	// The real route re-issues the cookie with a fresh 30-day Expires on every mint.
	http.SetCookie(w, &http.Cookie{Name: "__Secure-next-auth.session-token", Value: RotatedCookie, Path: "/", HttpOnly: true, Secure: true, Expires: time.Now().Add(30 * 24 * time.Hour).Truncate(time.Second)})
	// Not a real JWT: the CLI falls back to a four-minute cache when exp is unreadable.
	writeJSON(w, 200, map[string]any{"token": "access-token", "idToken": "id", "expires": time.Now().Add(30 * 24 * time.Hour).Format(time.RFC3339), "user": map[string]any{}})
}

// savedSearches serves GET /api/v3/searchalerts/savedsearch/ and /{id} in the
// shape recorded live on 2026-09-15 (ids and coordinates redacted). The
// service rejects calls without X-AppVersion, so the fake does too.
func (s *Server) savedSearches(w http.ResponseWriter, r *http.Request) {
	if r.Header.Get("X-AppVersion") == "" {
		writeJSON(w, 400, map[string]any{"type": "about:blank", "title": "Bad Request", "status": 400, "detail": "Required header 'X-AppVersion' is not present."})
		return
	}
	if !s.authed(w, r) {
		return
	}
	saved := map[string]any{
		"id":    SavedSearchID,
		"title": "thinkpad x1",
		"query": map[string]any{
			"latitude": 41.39, "longitude": 2.17, "keywords": "thinkpad x1", "max_sale_price": 400.0, "distance_in_km": 50,
			"order_by": "newest", "category_ids": []any{24200}, "condition": []any{"good", "fair"}, "country_code": "ES", "saved_search_id": SavedSearchID,
		},
		"placeholders":   map[string]any{},
		"alert":          map[string]any{"enabled": true, "hits": 0, "distance": 10000, "last_hits_reset_at": "2026-09-15T11:43:00Z"},
		"createdAt":      1789472639896,
		"default_view":   true,
		"experiment":     "exp_engagement_newvsold",
		"items":          nil,
		"description":    "All categories. Up to 400€. 08001 Barcelona. Up to 50 km",
		"location_label": "08001 Barcelona",
	}
	switch id := strings.TrimPrefix(r.URL.Path, "/api/v3/searchalerts/savedsearch/"); id {
	case "":
		writeJSON(w, 200, []any{saved})
	case SavedSearchID:
		delete(saved["query"].(map[string]any), "saved_search_id")
		writeJSON(w, 200, saved)
	default:
		writeJSON(w, 404, map[string]any{"status": "NOT_FOUND", "message": nil})
	}
}

func fakeImages(hash string, n int) []map[string]any {
	if n <= 0 {
		n = 1
	}
	imgs := make([]map[string]any, 0, n)
	for i := 1; i <= n; i++ {
		imgs = append(imgs, map[string]any{"id": "img" + strconv.Itoa(i), "urls": map[string]string{"small": "s", "medium": "m", "big": "https://cdn/" + hash + "-" + strconv.Itoa(i) + ".jpg"}})
	}
	return imgs
}

func (s *Server) searchItemJSON(it *Item) map[string]any {
	return map[string]any{
		"id": it.Hash, "user_id": it.Seller, "title": it.Title, "description": s.itemDesc(it), "category_id": 17000,
		"price":    map[string]any{"amount": it.Price, "currency": "EUR"},
		"images":   fakeImages(it.Hash, it.Images),
		"reserved": map[string]bool{"flag": it.Reserved}, "favorited": map[string]bool{"flag": s.Favorites[it.Hash]},
		"location": map[string]any{"latitude": 40.4, "longitude": -3.7, "postal_code": "28001", "city": "Madrid", "country_code": "ES"},
		"shipping": map[string]bool{"item_is_shippable": true, "user_allows_shipping": true},
		"web_slug": it.Slug, "created_at": it.Modified.UnixMilli(), "modified_at": it.Modified.UnixMilli(),
		"taxonomy": []map[string]any{{"id": 17000, "name": "Bikes"}, {"id": 17001, "name": "MTB"}},
	}
}

func (s *Server) userItemJSON(it *Item) map[string]any {
	return map[string]any{
		"id": it.Hash, "title": it.Title, "description": "desc", "slug": it.Slug, "user_id": it.Seller,
		"images":   fakeImages(it.Hash, it.Images),
		"price":    map[string]any{"amount": it.Price, "currency": "EUR"},
		"shipping": map[string]bool{"item_is_shippable": true},
		"reserved": map[string]bool{"flag": it.Reserved}, "sold": map[string]bool{"flag": it.Sold},
	}
}

func (s *Server) search(w http.ResponseWriter, r *http.Request) {
	s.mu.Lock()
	defer s.mu.Unlock()
	start := 0
	if r.URL.Query().Get("next_page") == "page2" {
		start = 40
	}
	var items []map[string]any
	for i := start; i < len(s.SearchOrder) && i < start+40; i++ {
		it := s.Items[s.SearchOrder[i]]
		if it.Removed {
			continue
		}
		items = append(items, s.searchItemJSON(it))
	}
	if items == nil {
		items = []map[string]any{}
	}
	next := ""
	if start == 0 && len(s.SearchOrder) > 40 {
		next = "page2"
	}
	w.Header().Set("x-wallapop-search-id", "search-id-1")
	writeJSON(w, 200, map[string]any{
		"data": map[string]any{"section": map[string]any{"type": "organic_search_results", "payload": map[string]any{"items": items}}},
		"meta": map[string]any{"next_page": next, "next_section_type": ""},
	})
}

func (s *Server) filters(w http.ResponseWriter, r *http.Request) {
	list := func(id, title, key string, opts ...string) map[string]any {
		var options []map[string]any
		for _, o := range opts {
			options = append(options, map[string]any{"id": o, "title": o, "is_selected": false})
		}
		return map[string]any{"id": id, "title": title, "type": "list",
			"search_params": map[string]any{"list_param": map[string]any{"param_key": key}},
			"type_data":     map[string]any{"source_data": map[string]any{"options_data": map[string]any{"options": options}}}}
	}
	filters := []map[string]any{
		{"id": "price", "title": "Price", "type": "slider", "search_params": map[string]any{"min_param": map[string]any{"param_key": "min_sale_price"}, "max_param": map[string]any{"param_key": "max_sale_price"}}},
		list("condition", "Condition", "condition", "new", "good"),
	}
	if r.URL.Query().Get("category_id") == "100" {
		filters = append(filters, list("brand", "Brand", "brand", "Toyota", "Seat"),
			map[string]any{"id": "km_cars", "title": "Km", "type": "slider", "search_params": map[string]any{"min_param": map[string]any{"param_key": "min_km"}, "max_param": map[string]any{"param_key": "max_km"}}})
	}
	writeJSON(w, 200, map[string]any{"selected_filters": []any{}, "filter_sections": []map[string]any{{"filters": filters}}})
}

func (s *Server) rawUser(hash, name, slug string) map[string]any {
	return map[string]any{
		"id": hash, "micro_name": name, "type": "normal", "web_slug": slug, "url_share": "https://es.wallapop.com/user/" + slug,
		"location":      map[string]any{"approximated_latitude": 41.39, "approximated_longitude": 2.17, "city": "Barcelona", "zip": "08001", "country_code": "ES"},
		"register_date": time.Date(2015, 3, 1, 0, 0, 0, 0, time.UTC).UnixMilli(),
		"seller_type":   map[string]any{"type": "private", "verified": true},
	}
}

func (s *Server) users(w http.ResponseWriter, r *http.Request) {
	rest := strings.TrimPrefix(r.URL.Path, "/api/v3/users/")
	hash, sub, _ := strings.Cut(rest, "/")
	if hash != OtherHash && hash != UserHash {
		writeJSON(w, 404, map[string]any{"code": 404, "message": "user not found"})
		return
	}
	switch sub {
	case "":
		writeJSON(w, 200, s.rawUser(hash, "Other Seller", "other-seller-68037934"))
	case "items":
		s.mu.Lock()
		var data []map[string]any
		for _, h := range s.SearchOrder {
			if it := s.Items[h]; it.Seller == hash && !it.Removed {
				data = append(data, s.userItemJSON(it))
			}
		}
		s.mu.Unlock()
		if data == nil {
			data = []map[string]any{}
		}
		writeJSON(w, 200, map[string]any{"data": data, "meta": map[string]any{}})
	case "stats":
		writeJSON(w, 200, map[string]any{"ratings": []map[string]any{{"type": "reviews", "value": 97}}, "counters": []map[string]any{{"type": "sold", "value": 36}, {"type": "publish", "value": 9}}, "rating_average": 4.9})
	case "reviews":
		writeJSON(w, 200, []map[string]any{{
			"item":   map[string]any{"id": "itemhash0001", "title": "Kimono"},
			"review": map[string]any{"id": "rev1", "date": time.Date(2026, 9, 11, 0, 0, 0, 0, time.UTC).UnixMilli(), "rating_over_five": 5, "comments": "todo bien"},
			"user":   map[string]any{"id": "buyerhash001", "micro_name": "Tania L."}, "type": "buy",
		}})
	default:
		writeJSON(w, 404, map[string]any{"code": 404, "message": "not found"})
	}
}

func (s *Server) items(w http.ResponseWriter, r *http.Request) {
	rest := strings.TrimPrefix(r.URL.Path, "/api/v3/items/")
	hash, action, _ := strings.Cut(rest, "/")
	s.mu.Lock()
	it, ok := s.Items[hash]
	malformed := s.MalformedItem
	s.mu.Unlock()
	if !ok || (it.Removed && action == "") {
		writeJSON(w, 404, map[string]any{"code": 404, "message": "item not found"})
		return
	}
	switch {
	case action == "" && r.Method == http.MethodGet:
		if malformed {
			w.WriteHeader(200)
			fmt.Fprint(w, "<html>not json</html>")
			return
		}
		writeJSON(w, 200, map[string]any{
			"id": it.Hash, "title": map[string]string{"original": it.Title}, "description": map[string]string{"original": s.itemDesc(it)},
			"taxonomy": []map[string]any{{"id": "17000", "name": "Bikes"}}, "user": map[string]any{"id": it.Seller}, "slug": it.Slug,
			"price":           map[string]any{"cash": map[string]any{"amount": it.Price, "currency": "EUR"}},
			"images":          fakeImages(it.Hash, it.Images),
			"location":        map[string]any{"latitude": 40.4, "longitude": -3.7, "city": "Madrid", "postal_code": "28001", "country_code": "ES"},
			"type_attributes": map[string]any{"condition": map[string]any{"value": s.itemCondition(it)}},
			"shipping":        map[string]bool{"item_is_shippable": true},
			"favorited":       map[string]bool{"flag": s.Favorites[it.Hash]},
			"counters":        map[string]int{"views": 12, "favorites": 3, "conversations": 1},
			"modified_date":   it.Modified.UnixMilli(),
		})
	case action == "" && r.Method == http.MethodDelete:
		if !s.authed(w, r) || !s.owned(w, it, 401) {
			return
		}
		s.mu.Lock()
		it.Removed = true
		s.mu.Unlock()
		w.WriteHeader(204)
	case action == "favorite" && r.Method == http.MethodPut:
		if !s.authed(w, r) {
			return
		}
		var body struct{ Favorited bool }
		_ = json.NewDecoder(r.Body).Decode(&body)
		s.mu.Lock()
		s.Favorites[hash] = body.Favorited
		s.mu.Unlock()
		w.WriteHeader(204)
	case action == "reserve" && r.Method == http.MethodPut:
		if !s.authed(w, r) || !s.owned(w, it, 401) {
			return
		}
		var body struct{ Reserved bool }
		_ = json.NewDecoder(r.Body).Decode(&body)
		s.mu.Lock()
		it.Reserved = body.Reserved
		s.mu.Unlock()
		w.WriteHeader(204)
	case action == "sold" && r.Method == http.MethodPut:
		if !s.authed(w, r) || !s.owned(w, it, 403) {
			return
		}
		s.mu.Lock()
		it.Sold = true
		s.mu.Unlock()
		w.WriteHeader(204)
	case action == "" && r.Method == http.MethodPut:
		s.editItem(w, r, it)
	default:
		writeJSON(w, 404, map[string]any{"code": 404, "message": "not found"})
	}
}

func (s *Server) itemPage(w http.ResponseWriter, r *http.Request) {
	slug := strings.TrimPrefix(r.URL.Path, "/item/")
	s.mu.Lock()
	var it *Item
	for _, cand := range s.Items {
		if cand.Slug == slug {
			it = cand
		}
	}
	s.mu.Unlock()
	if it == nil || it.Removed {
		w.WriteHeader(404)
		fmt.Fprint(w, "<html>gone</html>")
		return
	}
	item := map[string]any{
		"id": it.Hash, "userId": it.Seller, "title": map[string]any{"original": it.Title}, "description": map[string]any{"original": s.itemDesc(it)},
		"slug": it.Slug, "price": map[string]any{"cash": map[string]any{"amount": it.Price, "currency": "EUR"}},
		"flags":        map[string]bool{"reserved": it.Reserved, "sold": it.Sold, "expired": false, "onHold": false, "bumped": false, "favorited": false},
		"modifiedDate": it.Modified.UnixMilli(), "views": 12, "favorites": 3,
		"images":     fakeImages(it.Hash, it.Images),
		"location":   map[string]any{"latitude": 40.4, "longitude": -3.7, "city": "Madrid", "postalCode": "28001", "countryCode": "ES"},
		"shipping":   map[string]bool{"isItemShippable": true},
		"condition":  map[string]any{"value": s.itemCondition(it), "text": "Buen estado"},
		"taxonomies": []map[string]any{{"id": "17000", "name": "Bikes"}, {"id": "17001", "name": "MTB"}},
	}
	nd, _ := json.Marshal(map[string]any{"props": map[string]any{"pageProps": map[string]any{"item": item}}})
	w.Header().Set("Content-Type", "text/html")
	fmt.Fprintf(w, `<html><head></head><body><script id="__NEXT_DATA__" type="application/json">%s</script></body></html>`, nd)
}

func (s *Server) userPage(w http.ResponseWriter, r *http.Request) {
	slug := strings.TrimPrefix(r.URL.Path, "/user/")
	if slug != "other-seller-68037934" {
		w.WriteHeader(404)
		return
	}
	nd, _ := json.Marshal(map[string]any{"props": map[string]any{"pageProps": map[string]any{"user": map[string]any{"id": OtherHash, "microName": "Other Seller"}}}})
	w.Header().Set("Content-Type", "text/html")
	fmt.Fprintf(w, `<html><body><script id="__NEXT_DATA__" type="application/json">%s</script></body></html>`, nd)
}

func (s *Server) convJSON(c *Conversation) map[string]any {
	it := s.Items[c.Item]
	title, price, slug := "unknown", 0.0, ""
	if it != nil {
		title, price, slug = it.Title, it.Price, it.Slug
	}
	var msgs []map[string]any
	// Newest first, as the BFF does.
	for i := len(c.Messages) - 1; i >= 0; i-- {
		m := c.Messages[i]
		msgs = append(msgs, map[string]any{"id": m.ID, "from_self": m.FromSelf, "text": m.Text, "timestamp": m.At.UnixMilli(), "status": "read", "type": "text", "time_token": m.TimeToken})
	}
	if msgs == nil {
		msgs = []map[string]any{}
	}
	return map[string]any{
		"hash":            c.Hash,
		"sale":            map[string]any{"seller": map[string]string{"hash": c.Other}, "buyer": map[string]string{"hash": UserHash}},
		"with_user":       map[string]any{"hash": c.Other, "name": "Other Seller", "slug": "other-seller-68037934", "available": true, "blocked": false, "rating_average": 4.9, "reviews_count": 97},
		"item":            map[string]any{"hash": c.Item, "title": title, "status": "published", "price": map[string]any{"amount": price, "currency": "EUR"}, "slug": slug, "is_mine": false},
		"messages":        map[string]any{"messages": msgs, "next_from": ""},
		"unread_messages": c.Unread, "channel": c.Channel, "translatable": false, "topic_id": "", "items_count": 1,
	}
}

func (s *Server) inbox(w http.ResponseWriter, r *http.Request, archived bool) {
	if !s.authed(w, r) {
		return
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	var convs []map[string]any
	for _, c := range s.Conversations {
		if c.Archived == archived {
			convs = append(convs, s.convJSON(c))
		}
	}
	if convs == nil {
		convs = []map[string]any{}
	}
	writeJSON(w, 200, map[string]any{"user_hash": UserHash, "unread_messages": 0, "conversations": convs, "next_from": ""})
}

func (s *Server) conversation(w http.ResponseWriter, r *http.Request) {
	if !s.authed(w, r) {
		return
	}
	hash := strings.TrimPrefix(r.URL.Path, "/bff/messaging/conversation/")
	s.mu.Lock()
	c, ok := s.Conversations[hash]
	defer s.mu.Unlock()
	if !ok {
		writeJSON(w, 404, map[string]any{"code": 404, "message": "conversation not found"})
		return
	}
	writeJSON(w, 200, s.convJSON(c))
}

func (s *Server) createConversation(w http.ResponseWriter, r *http.Request) {
	if !s.authed(w, r) {
		return
	}
	var body struct {
		ItemHashID string `json:"item_hash_id"`
	}
	_ = json.NewDecoder(r.Body).Decode(&body)
	s.mu.Lock()
	defer s.mu.Unlock()
	s.CreateCalls++
	it, ok := s.Items[body.ItemHashID]
	if !ok {
		writeJSON(w, 404, map[string]any{"code": 404, "message": "item not found"})
		return
	}
	hash := fmt.Sprintf("newconv%05d", s.CreateCalls)
	c := &Conversation{Hash: hash, Item: it.Hash, Other: it.Seller, Channel: "chat." + it.Seller + "." + it.Hash + "." + UserHash}
	s.Conversations[hash] = c
	writeJSON(w, 201, map[string]any{"conversation_id": hash, "item_id": it.Hash, "other_user_id": it.Seller, "created_date": time.Now().UnixMilli(), "channel": c.Channel})
}

func (s *Server) archive(w http.ResponseWriter, r *http.Request, archived bool) {
	if !s.authed(w, r) {
		return
	}
	var body struct {
		IDs []string `json:"conversation_ids"`
	}
	_ = json.NewDecoder(r.Body).Decode(&body)
	s.mu.Lock()
	defer s.mu.Unlock()
	for _, id := range body.IDs {
		if c, ok := s.Conversations[id]; ok {
			if c.Archived == archived {
				w.WriteHeader(409)
				return
			}
			c.Archived = archived
		}
	}
	w.WriteHeader(204)
}

func (s *Server) publish(w http.ResponseWriter, r *http.Request) {
	if r.URL.Query().Get("auth") != "pam-token" {
		writeJSON(w, 403, map[string]any{"error": true, "status": 403, "message": "Forbidden"})
		return
	}
	// /publish/{pub}/{sub}/0/{channel}/0/{message}
	parts := strings.SplitN(strings.TrimPrefix(r.URL.Path, "/publish/"), "/", 6)
	if len(parts) < 6 {
		writeJSON(w, 400, []any{0, "bad path"})
		return
	}
	var msg, meta map[string]any
	_ = json.Unmarshal([]byte(parts[5]), &msg)
	_ = json.Unmarshal([]byte(r.URL.Query().Get("meta")), &meta)
	s.mu.Lock()
	s.Published = append(s.Published, Published{Channel: parts[3], Message: msg, Meta: meta, UUID: r.URL.Query().Get("uuid")})
	if convHash, _ := meta["conversation_hash"].(string); convHash != "" {
		if c, ok := s.Conversations[convHash]; ok {
			text, _ := msg["payload"].(map[string]any)["text"].(string)
			c.Messages = append(c.Messages, Message{ID: fmt.Sprint(msg["id"]), FromSelf: true, Text: text, At: time.Now(), TimeToken: fmt.Sprint(time.Now().UnixNano() / 100)})
		}
	}
	s.mu.Unlock()
	writeJSON(w, 200, []any{1, "Sent", fmt.Sprint(time.Now().UnixNano() / 100)})
}

// subscribe answers one incoming message the first time, then blocks until
// the client goes away, like the real long-poll.
func (s *Server) subscribe(w http.ResponseWriter, r *http.Request) {
	if r.URL.Query().Get("tt") == "0" {
		writeJSON(w, 200, map[string]any{"t": map[string]any{"t": "17000000000000000", "r": 1}, "m": []any{}})
		return
	}
	if r.URL.Query().Get("tt") == "17000000000000000" {
		d := map[string]any{"id": "in-1", "payload": map[string]string{"text": "hola desde el fake"}}
		u := map[string]any{"type": "text", "from_user_hash": OtherHash, "to_user_hash": UserHash, "conversation_hash": "convhash0001"}
		writeJSON(w, 200, map[string]any{"t": map[string]any{"t": "17000000000000001", "r": 1}, "m": []map[string]any{{"c": "inbox." + UserHash, "d": d, "u": u, "p": map[string]string{"t": "17000000000000001"}}}})
		return
	}
	<-r.Context().Done()
}

func (s *Server) messageAction(w http.ResponseWriter, r *http.Request) {
	var body map[string]any
	_ = json.NewDecoder(r.Body).Decode(&body)
	body["path"] = r.URL.Path
	s.mu.Lock()
	s.Actions = append(s.Actions, body)
	s.mu.Unlock()
	writeJSON(w, 200, map[string]any{"status": 200, "data": body})
}

func (s *Server) hook(w http.ResponseWriter, r *http.Request) {
	var raw json.RawMessage
	_ = json.NewDecoder(r.Body).Decode(&raw)
	s.mu.Lock()
	s.Hooks = append(s.Hooks, raw)
	status := s.WebhookStatus
	s.mu.Unlock()
	if status == 0 {
		status = 200
	}
	w.WriteHeader(status)
}

// categories serves the taxonomy; in create context leaves carry the
// attribute lists the upload flow validates against.
func (s *Server) categories(w http.ResponseWriter, r *http.Request) {
	attrs := map[string]any{}
	if r.URL.Query().Get("context") == "create" {
		attrs = map[string]any{"condition": map[string]any{"title": "condition"}, "size": map[string]any{"title": "size"}}
	}
	writeJSON(w, 200, map[string]any{"categories": []map[string]any{
		{"id": 100, "name": "Cars", "vertical_id": "cars", "attributes": map[string]any{"brand": map[string]any{"title": "brand"}}, "subcategories": []any{}},
		{"id": 17000, "name": "Bikes", "vertical_id": "consumer_goods", "subcategories": []map[string]any{{"id": 17001, "name": "MTB", "attributes": attrs, "subcategories": []any{}}}},
	}})
}

// itemDesc serves the stored description; pre-publish fixtures carry none,
// so they keep the old synthetic text.
func (s *Server) itemDesc(it *Item) string {
	if it.Description != "" {
		return it.Description
	}
	return "desc " + it.Title
}

func (s *Server) itemCondition(it *Item) string {
	if it.Condition != "" {
		return it.Condition
	}
	return "good"
}

// createItem mirrors POST /api/v3/items: multipart with image parts and an
// `item` JSON part. Missing title or images is a 400; success answers 200
// {"id"} and the listing appears in me items.
func (s *Server) createItem(w http.ResponseWriter, r *http.Request) {
	if !s.authed(w, r) {
		return
	}
	if r.Header.Get("Accept") != "application/vnd.upload-v2+json" {
		writeJSON(w, 405, map[string]any{"code": 405, "type": 1})
		return
	}
	mr, err := r.MultipartReader()
	if err != nil {
		writeJSON(w, 400, map[string]any{"code": 400, "message": "not multipart"})
		return
	}
	var itemJSON []byte
	images := 0
	for {
		part, err := mr.NextPart()
		if err != nil {
			break
		}
		name := part.FormName()
		body, _ := io.ReadAll(part)
		if name == "item" {
			itemJSON = body
		} else if name == "image" {
			images++
		}
	}
	var in struct {
		Attributes     map[string]any `json:"attributes"`
		CategoryLeafID string         `json:"category_leaf_id"`
	}
	_ = json.Unmarshal(itemJSON, &in)
	title, _ := in.Attributes["title"].(string)
	if title == "" || images == 0 {
		writeJSON(w, 400, map[string]any{"code": 400, "message": "title and images required"})
		return
	}
	price, _ := in.Attributes["price_amount"].(float64)
	cond, _ := in.Attributes["condition"].(string)
	desc, _ := in.Attributes["description"].(string)
	s.mu.Lock()
	s.CreateCalls++
	hash := "c" + strings.Repeat("0", 11-len(strconv.Itoa(s.CreateCalls))) + strconv.Itoa(s.CreateCalls)
	it := &Item{Hash: hash, Title: title, Description: desc, Price: price, Condition: cond, Images: images, Seller: UserHash, Modified: time.Now()}
	if it.Slug == "" {
		it.Slug = strings.ToLower(strings.ReplaceAll(title, " ", "-")) + "-1301645280"
	}
	s.Items[hash] = it
	s.SearchOrder = append(s.SearchOrder, hash)
	s.mu.Unlock()
	writeJSON(w, 200, map[string]any{"id": hash, "flags": map[string]any{}})
}

// editItem mirrors PUT /api/v3/items/{hash}: multipart like create, or plain
// JSON when pictures are unchanged. Only the owner's items are writable.
func (s *Server) editItem(w http.ResponseWriter, r *http.Request, it *Item) {
	if !s.authed(w, r) || !s.owned(w, it, 401) {
		return
	}
	var attrs map[string]any
	images := -1
	if strings.HasPrefix(r.Header.Get("Content-Type"), "multipart/") {
		mr, err := r.MultipartReader()
		if err != nil {
			writeJSON(w, 400, map[string]any{"code": 400, "message": "not multipart"})
			return
		}
		images = 0
		for {
			part, err := mr.NextPart()
			if err != nil {
				break
			}
			body, _ := io.ReadAll(part)
			if part.FormName() == "item" {
				_ = json.Unmarshal(body, &attrs)
			} else if part.FormName() == "image" {
				images++
			}
		}
	} else {
		_ = json.NewDecoder(r.Body).Decode(&attrs)
	}
	flat := attrs
	if inner, ok := attrs["attributes"].(map[string]any); ok {
		flat = inner
	}
	s.mu.Lock()
	if v, ok := flat["title"].(string); ok && v != "" {
		it.Title = v
	}
	if v, ok := flat["description"].(string); ok && v != "" {
		it.Description = v
	}
	if v, ok := flat["price_amount"].(float64); ok {
		it.Price = v
	}
	if v, ok := flat["condition"].(string); ok && v != "" {
		it.Condition = v
	}
	if images >= 0 {
		it.Images = images
	}
	it.Modified = time.Now()
	s.mu.Unlock()
	writeJSON(w, 200, map[string]any{})
}
