// docsgen writes the command reference for the docs site straight from the
// cobra tree, so the published flags are the binary's flags. CI runs it and
// fails if the working tree moves, which is what keeps the two in step.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Microck/wallapop-cli/internal/cli"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func main() {
	out := flag.String("out", "docs-site/content/docs/reference", "directory to write the reference into")
	flag.Parse()

	root := cli.CommandTree("0.0.0")
	if err := os.MkdirAll(*out, 0o755); err != nil {
		fail(err)
	}
	// The directory is rewritten wholesale: a command that disappears from the
	// binary has to disappear from the docs, and leaving the old page behind is
	// exactly the drift this generator exists to prevent.
	if err := clearGenerated(*out); err != nil {
		fail(err)
	}

	var globals strings.Builder
	globals.WriteString("---\ntitle: Global flags\ndescription: Flags available on every command.\n---\n\n{/* Generated by cmd/docsgen from the cobra tree. Do not edit by hand. */}\n\n")
	writeFlags(&globals, root)
	if err := os.WriteFile(filepath.Join(*out, "global-flags.mdx"), []byte(globals.String()), 0o644); err != nil {
		fail(err)
	}
	pages := []string{"global-flags"}
	for _, cmd := range topLevel(root) {
		name := cmd.Name()
		body := renderGroup(cmd)
		if err := os.WriteFile(filepath.Join(*out, name+".mdx"), []byte(body), 0o644); err != nil {
			fail(err)
		}
		pages = append(pages, name)
	}

	meta := "{\n  \"title\": \"Command reference\",\n  \"description\": \"Every command, generated from the binary\",\n  \"pages\": [\n    \"index\",\n"
	for i, p := range pages {
		meta += "    \"" + p + "\""
		if i < len(pages)-1 {
			meta += ","
		}
		meta += "\n"
	}
	meta += "  ]\n}\n"
	if err := os.WriteFile(filepath.Join(*out, "meta.json"), []byte(meta), 0o644); err != nil {
		fail(err)
	}
	fmt.Fprintf(os.Stderr, "wrote %d reference pages to %s\n", len(pages), *out)
}

// clearGenerated removes the mdx pages and the meta this tool owns, leaving
// anything a human added in the same directory alone.
func clearGenerated(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		// index.mdx is written by hand and explains what the rest of the
		// directory is; only the per-command pages are ours to delete.
		if e.Name() == "index.mdx" {
			continue
		}
		if strings.HasSuffix(e.Name(), ".mdx") || e.Name() == "meta.json" {
			if err := os.Remove(filepath.Join(dir, e.Name())); err != nil {
				return err
			}
		}
	}
	return nil
}

func topLevel(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, c := range root.Commands() {
		if c.Hidden || c.Name() == "help" || c.Name() == "completion" {
			continue
		}
		out = append(out, c)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name() < out[j].Name() })
	return out
}

// renderGroup writes one page per top-level command, with its subcommands as
// sections, which keeps the sidebar the shape of the noun-verb command set.
func renderGroup(cmd *cobra.Command) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntitle: %s\ndescription: %s\n---\n\n", cmd.Name(), yamlSafe(cmd.Short))
	b.WriteString("{/* Generated by cmd/docsgen from the cobra tree. Do not edit by hand. */}\n\n")
	renderCommand(&b, cmd, 2)
	for _, sub := range cmd.Commands() {
		if sub.Hidden || sub.Name() == "help" {
			continue
		}
		renderCommand(&b, sub, 2)
		for _, leaf := range sub.Commands() {
			if leaf.Hidden || leaf.Name() == "help" {
				continue
			}
			renderCommand(&b, leaf, 3)
		}
	}
	return b.String()
}

func renderCommand(b *strings.Builder, cmd *cobra.Command, level int) {
	if !cmd.Runnable() && !cmd.HasSubCommands() {
		return
	}
	fmt.Fprintf(b, "%s `%s`\n\n", strings.Repeat("#", level), cmd.CommandPath())
	if cmd.Short != "" {
		fmt.Fprintf(b, "%s\n\n", mdxProse(cmd.Short))
	}
	if cmd.Runnable() {
		fmt.Fprintf(b, "```bash\n%s\n```\n\n", cmd.UseLine())
	}
	if long := strings.TrimSpace(cmd.Long); long != "" && long != cmd.Short {
		body, examples := splitExamples(long)
		if body != "" {
			fmt.Fprintf(b, "%s\n\n", mdxProse(body))
		}
		if examples != "" {
			fmt.Fprintf(b, "```bash\n%s\n```\n\n", examples)
		}
	}
	writeFlags(b, cmd)
}

// splitExamples pulls the trailing "Examples:" block out of a Long string so it
// renders as a code block instead of a wall of prose.
func splitExamples(long string) (body, examples string) {
	i := strings.Index(long, "Examples:")
	if i < 0 {
		return long, ""
	}
	body = strings.TrimSpace(long[:i])
	var lines []string
	for _, l := range strings.Split(long[i+len("Examples:"):], "\n") {
		if t := strings.TrimSpace(l); t != "" {
			lines = append(lines, t)
		}
	}
	return body, strings.Join(lines, "\n")
}

func writeFlags(b *strings.Builder, cmd *cobra.Command) {
	type row struct{ name, typ, def, usage string }
	var rows []row
	cmd.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		name := "--" + f.Name
		if f.Shorthand != "" {
			name = "-" + f.Shorthand + ", " + name
		}
		rows = append(rows, row{name, f.Value.Type(), f.DefValue, f.Usage})
	})
	if len(rows) == 0 {
		return
	}
	b.WriteString("| Flag | Type | Default | Description |\n| --- | --- | --- | --- |\n")
	for _, r := range rows {
		def := r.def
		if def == "" {
			def = "-"
		} else {
			def = "`" + def + "`"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", r.name, r.typ, def, mdSafe(r.usage))
	}
	b.WriteString("\n")
}

func yamlSafe(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	if strings.ContainsAny(s, ":#\"'") {
		return "\"" + strings.ReplaceAll(s, "\"", "\\\"") + "\""
	}
	return s
}

func mdSafe(s string) string {
	s = strings.ReplaceAll(strings.ReplaceAll(s, "|", "\\|"), "\n", " ")
	return mdxProse(s)
}

// mdxProse escapes the two characters MDX reads as syntax. Help strings are
// written for a terminal, so a stray `<` or `{` in one would otherwise fail the
// docs build long after the person who wrote it moved on.
func mdxProse(s string) string {
	return strings.NewReplacer("{", "\\{", "<", "\\<").Replace(s)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "docsgen:", err)
	os.Exit(1)
}
