// Command bundle-galleton builds the pinned upstream daemon for release embedding.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"

	"github.com/Microck/wallapop-cli/internal/galleton/bundle"
)

func main() {
	all := flag.Bool("all", false, "prepare all release OS/architecture pairs")
	flag.Parse()
	if err := build(*all); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
func build(all bool) error {
	cmd := exec.Command("go", "mod", "download", "-json", bundle.Module+"@"+bundle.Version)
	raw, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("download pinned Galleton: %w", err)
	}
	var mod struct{ Dir, Sum, GoModSum string }
	if err := json.Unmarshal(raw, &mod); err != nil {
		return err
	}
	if mod.Sum != bundle.Sum || mod.GoModSum != bundle.ModSum {
		return fmt.Errorf("galleton module checksum mismatch")
	}
	targets := [][2]string{{runtime.GOOS, runtime.GOARCH}}
	if all {
		targets = [][2]string{{"linux", "amd64"}, {"linux", "arm64"}, {"darwin", "amd64"}, {"darwin", "arm64"}, {"windows", "amd64"}, {"windows", "arm64"}}
	}
	root, err := filepath.Abs("internal/galleton/bundle")
	if err != nil {
		return err
	}
	for _, target := range targets {
		suffix := target[0] + "_" + target[1]
		name := "galleton_" + suffix + ".bin"
		cmd := exec.Command("go", "build", "-trimpath", "-buildvcs=false", "-ldflags=-s -w", "-o", filepath.Join(root, name), "./cmd/galleton")
		cmd.Dir = mod.Dir
		cmd.Env = append(os.Environ(), "CGO_ENABLED=0", "GOOS="+target[0], "GOARCH="+target[1], "GOWORK=off", "GOFLAGS=")
		cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
		if err := cmd.Run(); err != nil {
			return err
		}
		src := fmt.Sprintf(`// Code generated by cmd/bundle-galleton; DO NOT EDIT.
//go:build galleton_bundle && %s && %s

package bundle

import _ "embed"

//go:embed %s
var Binary []byte
`, target[0], target[1], name)
		if err := os.WriteFile(filepath.Join(root, "payload_"+suffix+".go"), []byte(src), 0644); err != nil {
			return err
		}
	}
	return nil
}
